model_providers:
  openai:
    provider: openai
    api_key: ${OPENAI_API_KEY}

models:
  codex_agent_model:
    model_provider: openai
    model: gpt-4o
    max_tokens: 8192
    temperature: 0.4
    top_p: 1
    top_k: 0
    max_retries: 6
    parallel_tool_calls: true

allow_mcp_servers: []
mcp_servers: {}

agents:
  trae_agent:
    enable_lakeview: false
    model: codex_agent_model
    max_steps: 120
    tools:
      - bash
      - str_replace_based_edit_tool
      - sequentialthinking
      - task_done
