[llm]
model = "gpt-5-2025-08-07"
base_url = "https://api.openai.com/v1"
custom_llm_provider = "openai"
max_input_tokens = 128000
max_output_tokens = 4096
input_cost_per_token = 0.0
output_cost_per_token = 0.0
ollama_base_url = ""
drop_params = false
